### ISSUE TITLE
Analyzer does not decode command 0xFF

### ISSUE THREAD

**Issue by pascalheude** [Jackjan4/NRF24L01-analyzer#1]
According to NRF24L01+ datasheet (see table 19), 0xFF command is a NOP command.
The analyzer does not decode this command, as you can see below :
![image](https://github.com/Jackjan4/NRF24L01-analyzer/assets/29336716/9431fe2a-6457-417e-baa8-bb0386054d9d)

**Comment by Jackjan4** [comment]
You're right! Didn't give this command much attentation until now. I will fix it, would be nice if you could look into it, when done.

**Comment by pascalheude** [comment]
I installed the new version 0.2.0 and I got the following error:
![image](https://github.com/Jackjan4/NRF24L01-analyzer/assets/29336716/6190fa0c-07fa-4cf3-9830-d392e65208c9)
I think this is due to tab character in the python code. If you replace tab by space, it will solve the problem.
I've attached the capture file (in zip file) which raises the error, so you can perform some tests.
[frames from start.zip](https://github.com/Jackjan4/NRF24L01-analyzer/files/11572724/frames.from.start.zip)

**Comment by Jackjan4** [comment]
Thanks for your sample! I didn't have a NRF24 at hand to test it myself. I fixed the wrong tab indentations that GitHub editor included in the file... 
Changes are now in v.0.2.2
I tested it with your sample and now NOP seems to work fine.

![Unbenannt](https://github.com/Jackjan4/NRF24L01-analyzer/assets/17764195/f52dc106-b036-488c-9a33-dff13e66fa47)

**Comment by pascalheude** [comment]
Closed with tag "Version 0.2.2".
